-- FishMap Pro cloud storage
-- Run this SQL in Supabase SQL Editor.

create table if not exists public.fishmap_data (
    id bigint generated by default as identity primary key,
    device_id text not null unique,
    data jsonb not null,
    updated_at timestamptz not null default now()
);

alter table public.fishmap_data enable row level security;

-- Prototype policy:
-- allows anonymous clients to read/write rows.
-- Before public production deployment, replace this with
-- authenticated user policies tied to auth.uid().

drop policy if exists "fishmap anon read" on public.fishmap_data;
create policy "fishmap anon read"
on public.fishmap_data
for select
to anon
using (true);

drop policy if exists "fishmap anon insert" on public.fishmap_data;
create policy "fishmap anon insert"
on public.fishmap_data
for insert
to anon
with check (true);

drop policy if exists "fishmap anon update" on public.fishmap_data;
create policy "fishmap anon update"
on public.fishmap_data
for update
to anon
using (true)
with check (true);
